import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <main className="mx-auto mt-[100px] grid w-full max-w-7xl items-start gap-6 md:grid-cols-[180px_1fr] lg:grid-cols-[250px_1fr]">
            <nav
              className="grid gap-4 text-sm text-muted-foreground"
              x-chunk="dashboard-04-chunk-0"
            >
              <Link href="#" className="font-semibold text-primary">
                PRODUCTS
              </Link>
              <Link href="#">OUTDOOR</Link>
              <Link href="#">LIVING ROOMS</Link>
              <Link href="#">KITCHEN</Link>
              <Link href="#">BATHROOMS</Link>
              <Link href="#">GARDEN</Link>
            </nav>
            <div>{children}</div>
          </main>
          <Toaster toastOptions={{
            className: "h-[64px]"
          }}/>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
