import "@/styles/globals.css";

import { Inter } from "next/font/google";

import NavBar from "@/components/page-components/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <main className="mx-auto max-w-7xl mt-[90px] py-8 min-h-[calc(100vh-90px)] z-10">{children}</main>
    </>
  );
}
